### ISSUE TITLE
Grouping of subjects is done by their string value. Change to sets.

### ISSUE THREAD

**Issue by odumitrasc** [CSS-Conflict-WS2017-18/WikiConflict#10]
Also, look into how we can use supersets. Example
support( A, B)
We also calculate support for everything that has A,B
For example (A,B,C)

**Comment by odumitrasc** [comment]
I would like to discuss some things:

- this task is about changing phase 2 based on strings and not ids
- it is also about making the context sets and tackling super-sets, right? :)

**Comment by dkeske** [comment]
This task is not about changing phase 2.
In wikiwho data, when we calc support for subjects, we use the string representation of a list. We should change it to sets

**Comment by dkeske** [comment]
Strings can be in an index of a dataframe. I am not sure if sets can be also. So im not sure what will happen when we do a group by

**Comment by odumitrasc** [comment]
I think it works good :D

**Comment by odumitrasc** [comment]
Done :)
