### ISSUE TITLE
Wikiwho api removes revisions, the number returned is lower than expexted

### ISSUE THREAD

**Issue by dkeske** [CSS-Conflict-WS2017-18/WikiConflict#4]

**Comment by dkeske** [comment]
Solved, but the number of revisions is still not complete always

**Comment by dkeske** [comment]
Can be reproduced on Yugoslavia article

**Comment by OmarKAly22** [comment]
Could you give example here Daniel ?

**Comment by dkeske** [comment]
You can try downloading the Yugoslavia article. This is not a big priority, we can do it later

**Comment by dkeske** [comment]
We found out later that this is due to wikiwho removing revisions that are considered vandalism.
