### ISSUE TITLE
Assigning a deletion to a correct revision

### ISSUE THREAD

**Issue by dkeske** [CSS-Conflict-WS2017-18/WikiConflict#6]
I am not sure, but this needs to be checked
If something was deleted in revision 2, we want it to be assigned to rev 2
example
rev0: 1 2 3 4 5 6 7 8 9 10 11
rev1: 1 2 3 4 5 [-6 -7] 8 9 10 11
Here, out list for token 6 and 7 would have revision 1 in it
We look for the context of the change in revision 0
Do we assign the change object to revision 0 or 1?

**Comment by odumitrasc** [comment]
rev0: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
rev1: 1 2 3 4 5 [-6 -7] 8 9 [-10 -11] 12 13 14 15

assign revision 1 for both edits while taking the context from rev 0 should be the right thing to do, as u have as a reference point the revision before.

**Comment by OmarKAly22** [comment]
It was in revision 0 and deleted in revision 1 so It should be assigned to revision 1

**Comment by dkeske** [comment]
Maybe i confused us a little with notation
rev0: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
rev1: 1 2 3 4 5       8 9           12 13 14 15 - so here, we removed 6,7,10,11

What we do now is, we say these were actually done in previous revision, 0. So we can find them there.
this is this strange line
```
for rev_id in token_dict['out']:
            deleted_tokens[str(revisions[revisions_indexed[str(rev_id)]-1])].append(token_id)
```
Here, every delete gets indexed one revision before (thus -1).
so when we do parsing
```
def parse_revisions(rev_content):
....
   if reinserted_tokens[rev_id] != [] or deleted_tokens[rev_id] != []:
```
we actually find the token in text. This makes me believe we now assign deletions to revision 0

**Comment by dkeske** [comment]
This is important for many reasons:
1. We get the wrong editor when we clean the data
2. If we calculate time, we have a wrong revision
3. If we count revision, we get a (little bit) bigger number

**Comment by odumitrasc** [comment]
Done :)
