### ISSUE TITLE
Performing second level clustering on strings instead of IDs

### ISSUE THREAD

**Issue by dkeske** [CSS-Conflict-WS2017-18/WikiConflict#7]
At the moment we cannot combine 2 similar controversies happening in a different part of the article

One solution could be to perform the second level clustering on the token string values (like in the paper), not on IDs

This is a question for first level clustering also.

**Comment by odumitrasc** [comment]
I would definitely not do the clustering phase one on strings. 

**Motivation** - we will remove the best thing that we have extra in comparison to the paper - granularity.

For clustering phase2 - based on strings it might be useful to discover a controversy subject in an article that takes place in different parts of that article, but still I would still keep the token based clustering as they can be used for different reasons.

**Comment by dkeske** [comment]
We could use this step in ranking? To put clusters similar in string close to each other

**Comment by odumitrasc** [comment]
After last meeting's discussion it is done by strings, not ids
